backend:
  name: git-gateway
  branch: master # Branch to update

media_folder: "/src/image/uploads"
public_folder: "/src/image/uploads"

publish_mode: editorial_workflow
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

# publish_mode: editorial_workflow
collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Favicon"
        name: "favicon"
        file: "/_data/head.json"
        fields:
          - label: Favicon
            name: "fav"
            widget: "image"


      - label: "Header settings"
        name: "menu"
        file: "/_data/header.json"
        fields:
          - label: Header Nav Items
            name: menu
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: link_name, widget: string }
              - { label: URL, name: link_href, widget: string }
          - label: "Download"
            name: "download_file"
            widget: "file"
            default: "src/image/uploads/footer_bg.png"
            media_library:
              config:
                multiple: true

      - label: "Footer settings"
        name: "links"
        file: "/_data/footer.json"
        fields:
          - label: Footer Social Items
            name: socials_link
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: logo social, name: socials, widget: image }
              - { label: URL, name: link_href, widget: string }

          - label: Footer Nav Items
            name: menu
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: link_name, widget: string }
              - { label: URL, name: link_href, widget: string }

          - label: Download_file_footer
            name: files_load
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: file_name, name: name_file, widget: string }
              - { label: file_size, name: size_file, widget: string }
              - { label: file_download, name: value, widget: file }


      - label: "Meta settings for article page"
        name: "meta"
        file: "/_data/article/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"

      - label: "Meta settings for homepage"
        name: "meta_2"
        file: "/_data/homepage/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"

      - label: "Meta settings for homepage_alt"
        name: "meta_3"
        file: "/_data/homepage_alt/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"

      - label: "Meta settings for basic_content"
        name: "meta_4"
        file: "/_data/basic_cont/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"

      - label: "Meta settings for biz_strategy"
        name: "meta_5"
        file: "/_data/biz_strategy/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"

      - label: "Meta settings for finance"
        name: "meta_6"
        file: "/_data/finance/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"

      - label: "Meta settings for rich_story"
        name: "meta_7"
        file: "/_data/rich_story/meta.json"
        fields:
          - label: Meta Title
            name: "meta_title"
            widget: "string"
          - label: Meta Desc
            name: "meta_desc"
            widget: "string"


  # Our blog layout
  - label: "Article"
    name: "Article"
    folder: "/article"
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Meta_title", name: "meta_title", widget: "string" }
      - { label: "Meta_description", name: "meta_desc", widget: "string" }

      - { label: "Background_post_img", name: "bg_img_post", widget: "image" }

      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "data_title", widget: "string" }
      - { label: "Data", name: "data_info", widget: "datetime", picker_utc: false, format: "LL"}
      - { label: "1_section_title", name: "first_title", widget: "string" }
      - { label: "1_section_desc", name: "first_desc", widget: "text" }

      - { label: "2_section_image", name: "second_img", widget: "image" }
      - { label: "2_section_alt", name: "second_img_alt", widget: "string" }
      - { label: "2_section_name", name: "second_text", widget: "string" }
      - { label: "2_section_title", name: "second_title", widget: "string" }
      - { label: "2_section_desc", name: "second_desc", widget: "text" }
      - { label: "2_section_btn_text", name: "second_btn_text", widget: "string" }
      - { label: "2_section_btn_href", name: "second_btn_href", widget: "string" }

      - { label: "3_section_name", name: "third_desc", widget: "string" }
      - { label: "3_section_title", name: "third_author", widget: "string" }
      - { label: "3_section_desc", name: "third_title", widget: "text" }

      - { label: "4_section_image", name: "fourth_img", widget: "image" }
      - { label: "4_section_alt", name: "fourth_img_alt", widget: "string" }
      - { label: "4_section_name", name: "fourth_text", widget: "string" }
      - { label: "4_section_title", name: "fourth_title", widget: "string" }
      - { label: "4_section_desc", name: "fourth_desc", widget: "text" }
      - { label: "4_section_btn_text", name: "fourth_btn_text", widget: "string" }
      - { label: "4_section_btn_href", name: "fourth_btn_href", widget: "string" }

      - { label: "5_section_image", name: "five_img", widget: "image" }
      - { label: "5_section_alt", name: "five_img_alt", widget: "string" }
      - { label: "5_section_id", name: "five_id_video", widget: "string" }

      - { label: "6_section_name", name: "sixth_title", widget: "string" }
      - { label: "6_section_title", name: "sixth_desc", widget: "string" }
      - { label: "6_section_desc", name: "sixth_title_list", widget: "text" }
      - { label: "6_section_list", name: "sixth_list", widget: "markdown" }

      - { label: "7_section_image", name: "seventh_img", widget: "image" }
      - { label: "7_section_alt", name: "seventh_img_alt", widget: "string" }
      - { label: "7_section_name", name: "seventh_text", widget: "string" }
      - { label: "7_section_title", name: "seventh_title", widget: "string" }
      - { label: "7_section_desc", name: "seventh_desc", widget: "text" }
      - { label: "7_section_btn_text", name: "seventh_btn_text", widget: "string" }
      - { label: "7_section_btn_href", name: "seventh_btn_href", widget: "string" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["homes"]


  # Our pages e.g. Works
  - label: "Page Settings"
    name: "Page settings"
    editor:
      preview: false
    files:
      - label: "Homepage Setting"
        name: "Homepage_Setting"
        file: "/_data/homepage_alt/presentation.json"
        fields:
          - { label: "ID video", name: "id_video", widget: "string" }
          - { label: "Preview Image", name: "imgPreview", widget: "image" }


      - label: "Homepage_alt Setting"
        name: "Homepage_alt_Setting"
        file: "/_data/homepage/presentation.json"
        fields:
          - label: ID video
            name: "id_video"
            widget: "string"
          - label: Previe Image
            name: "imgPreview"
            widget: "image"

      - label: "Biz_strategy page Setting"
        name: "Biz_strategy_page_Setting"
        file: "/_data/biz_strategy/presentation.json"
        fields:
          - label: ID video
            name: "id_video"
            widget: "string"
          - label: Previe Image
            name: "imgPreview"
            widget: "image"

      - label: "Basic_content page Setting"
        name: "Basic_content_page_Setting"
        file: "/_data/basic_cont/basic_video.json"
        fields:
          - label: ID video
            name: "id_video"
            widget: "string"
          - label: Previe Image
            name: "img"
            widget: "image"



